"""initial registry schema

Revision ID: 384023802c39
Revises: 
Create Date: 2026-09-20 15:04:15.015567
"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '384023802c39'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packages',
    sa.Column('id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('workflow_id', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('engine_range', sa.String(length=64), nullable=False),
    sa.Column('email_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source_corpus_id', sa.String(length=256), nullable=False),
    sa.Column('created_by', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('manifest', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=False),
    sa.Column('eval_report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('eval_report_sha256', sa.String(length=64), nullable=True),
    sa.Column('gate_failed', sa.Boolean(), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'PUBLISHED', 'PROMOTED', 'DEPRECATED', 'WITHDRAWN', 'ROLLED_BACK', name='package_state', native_enum=False, length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'workflow_id', 'version', name='uq_package_coordinate')
    )
    op.create_index('ix_packages_workflow', 'packages', ['client_id', 'workflow_id'], unique=False)
    op.create_table('activations',
    sa.Column('id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('workflow_id', sa.String(length=128), nullable=False),
    sa.Column('active_package_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=True),
    sa.Column('previous_package_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['active_package_id'], ['packages.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['previous_package_id'], ['packages.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'workflow_id', name='uq_activation_workflow')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('package_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(length=256), nullable=False),
    sa.Column('reviewed_by', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('package_id', 'path', name='uq_artifact_path')
    )
    op.create_table('promotions',
    sa.Column('id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('package_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('promoted_by', sa.String(length=256), nullable=False),
    sa.Column('promoted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eval_report_sha256', sa.String(length=64), nullable=False),
    sa.Column('manifest_sha256', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signoffs',
    sa.Column('id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('package_id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('identity', sa.String(length=256), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eval_report_sha256', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('signoffs')
    op.drop_table('promotions')
    op.drop_table('artifacts')
    op.drop_table('activations')
    op.drop_index('ix_packages_workflow', table_name='packages')
    op.drop_table('packages')
    # ### end Alembic commands ###
