"""learning runs

Revision ID: e6c3b2445387
Revises: 384023802c39
Create Date: 2026-10-03 20:18:57.606435
"""
from __future__ import annotations

from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e6c3b2445387'
down_revision: str | None = '384023802c39'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_runs',
    sa.Column('id', sa.String(length=36).with_variant(sa.UUID(as_uuid=False), 'postgresql'), nullable=False),
    sa.Column('client_id', sa.String(length=128), nullable=False),
    sa.Column('usecase', sa.String(length=128), nullable=False),
    sa.Column('object_name', sa.String(length=128), nullable=True),
    sa.Column('pattern_name', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=1024), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=True),
    sa.Column('ground_truth', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('reference_text', sa.Text(), nullable=True),
    sa.Column('base_version', sa.String(length=32), nullable=True),
    sa.Column('result_version', sa.String(length=32), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('passed_before', sa.Boolean(), nullable=False),
    sa.Column('passed_after', sa.Boolean(), nullable=True),
    sa.Column('verdict_before', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('verdict_after', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('attempts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('skill_path', sa.String(length=512), nullable=True),
    sa.Column('skill_markdown', sa.Text(), nullable=True),
    sa.Column('error', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('generated_by', sa.String(length=256), nullable=False),
    sa.Column('requested_by', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_learning_runs_pattern', 'learning_runs', ['client_id', 'usecase', 'pattern_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_learning_runs_pattern', table_name='learning_runs')
    op.drop_table('learning_runs')
    # ### end Alembic commands ###
